### ISSUE TITLE
Namespace reorg of masakari breaks chef recipes

### ISSUE THREAD

**Issue by tybritten** [ntt-sic/masakari-deploy#1]
The namespace changes in https://github.com/ntt-sic/masakari/pull/9 (masakari-, new conf file locations, etc) have broken the chef scripts here. I'm fixing them now.

**Comment by toshikazu0314** [comment]
@vmtyler Yes, it does affect. Please send pull request once you fixed.

**Comment by tybritten** [comment]
I think I have it fixed, I'm just doing the testing now, then I'll send up a PR
