### ISSUE TITLE
Error vagrant up (ubuntu controller)

### ISSUE THREAD

**Issue by takahiro-impara** [ntt-sic/masakari-deploy#12]
When I tried to deploy ubuntu controller, I saw some error messages and failed to deploy.

==> controller:   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1028, in run_setup
==> controller: 
==> controller:     raise DistutilsError("Setup script exited with %s" % (v.args[0],))
==> controller: 
==> controller: distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

how can I fix this problem?

**Comment by sampathP** [comment]
Seems like you dont have required pkgs installed.
Is there any errors in vagrent chef logs?
Could you please try after this?
sudo apt-get install build-essential python-dev

**Comment by takahiro-impara** [comment]
Thank you for your message.
After I tried that command, I could deploy Masakari instances.

Thank you so much.

**Comment by sampathP** [comment]
Great.. you are welcome
