### ISSUE TITLE
masakari-controller start failed

### ISSUE THREAD

**Issue by idonotknow** [ntt-sic/masakari-deploy#8]
I found masakari-controller start failed because of not enough information to determine URL. Something related to keystone, any suggestion to solve this issue?

**Comment by muroi** [comment]
@idonotknow Could you show us the details for your problem? We've not hit the problem ever.

**Comment by xandrohh** [comment]
@muroi I hit the same problem when trying masakari-deploy. When masakari-controller starts, I get the following in the logfile:

Apr 19 09:04:42  masakari(7700): ERROR: --MonitoringMessage--ID:[RecoveryController_0003]An error during initializing masakari controller: Not enough information to determine URL. Provide either auth_url or endpoint'
Apr 19 09:04:42  masakari(7700): ERROR: <type 'exceptions.OSError'>'
Apr 19 09:04:42  masakari(7700): ERROR: [Errno 17] File exists: '/var/log/masakari/''
Apr 19 09:04:42  masakari(7700): ERROR:   File "/opt/masakari/controller/masakari_controller.py", line 93, in **init**
    os.makedirs(log_dir)
'
Apr 19 09:04:42  masakari(7700): ERROR:   File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
'

I assume, the keystoneclient has problems to authenticate. My configuration is as follows:

cat /etc/masakari/masakari-controller.conf

[wsgi]
server_port = 15868

[db]
drivername = mysql
host = 192.168.50.10
name = vm_ha
user = root
passwd = password
charset = utf8
lock_retry_max_cnt = 5
innodb_lock_wait_timeout = 10

[log]
log_level = info

[recover_starter]
interval_to_be_retry = 300
max_retry_cnt = 3
semaphore_multiplicity = 5
notification_time_difference = 240
node_err_wait = 180
api_max_retry_cnt = 3
api_retry_interval = 10
recovery_max_retry_cnt = 6
recovery_retry_interval = 10
api_check_interval = 1
api_check_max_cnt = 30
notification_expiration_sec = 300

[nova]
domain = Default
admin_user = admin
admin_password = openstack
auth_url =  http://192.168.50.10:5000
project_name = admin

[vmha_data_manage]
period = 30

**Comment by muroi** [comment]
Thanks details.

I found the diff between my config and your config. Did you change admin_password in nova section? Masakari-deploy deploys devstack admin password with 'password' but your config looks 'openstack'. My config is following:

[nova]
domain = Default
admin_user = admin
admin_password = password
auth_url =  http://192.168.50.10:5000
project_name = admin

**Comment by idonotknow** [comment]
sorry for delay，mine is the same as yours，but still got failed

**Comment by xandrohh** [comment]
changing the password did not help. If this was the error there would be an authentication error in keystone logs, but I don't see anything there.
maybe can you reinstall masakari-deploy with the current code?

**Comment by muroi** [comment]
I reinstalled masakari-deploy and i finally hit the issue.  I think the root problem is differences of python-keystoneclient version.  I use 2.3.1 to test Masakari itself, but the version masakari-deploy deploys is 1.7.2.  And the older version hits the client's bug[1].

Now I'm checking Masakari works with stable/mitaka branch and then I'll commit a change to resolve the bug. If you want to resolve the bug immediately and make Masakari work in local, please change [2] as following in local.

```
        ks_client = keystone_client.Client(self.KEYSTONE_API_VERSION,
-                                           session=sess)
+                                           session=sess, auth_url=auth_args['auth_url'])
```
1. https://bugs.launchpad.net/python-keystoneclient/+bug/1513839
2. https://github.com/ntt-sic/masakari/blob/master/masakari-controller/controller/masakari_util.py#L560

**Comment by ghost** [comment]
Below configuration in masakari-controll.conf is worked for me 

[nova]
auth_url = http://controller:35357
auth_type = password
domain = default
user_domain_name = default
region_name = RegionOne
project_name = service
admin_user = nova
admin_password = NOVA_PASS
